version: '2'
services:

  grafana:
    image:
      grafana/grafana
    ports:
      - 6001:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana:/var/lib/grafana
    links:
      - influxdb
    restart:
      always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED:  "true"
      GF_AUTH_BASIC_ENABLED:    "false"

  influxdb:
    image:
      influxdb
    ports:
      - 6002:8086
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./influxdb:/var/lib/influxdb
    restart:
      always
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
